### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by UlrichRaab** [dvdciri/daggraph#19]
Hello

i wanted to try this lib and installed it using npm install -g daggraph without errors. When i try to create the graph i get the following error:

`/usr/local/lib/node_modules/daggraph/node_modules/inquirer/lib/prompts/list.js:32
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);`

`SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Function.promptModule.restoreDefaultPrompts (/usr/local/lib/node_modules/daggraph/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/usr/local/lib/node_modules/daggraph/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/daggraph/node_modules/inquirer/lib/inquirer.js:77:28)`

**Comment by cesarferreira** [comment]
What node version do you have installed?

**Comment by dvdciri** [comment]
@UlrichRaab I believe is because you're using a old version of node, please update that and try again.

**Comment by UlrichRaab** [comment]
I have updated node to the latest version and it works. Thank you.

**Comment by kotya341** [comment]
witch is the min node version that you support?
