### ISSUE TITLE
Daggraph fails with TypeError

### ISSUE THREAD

**Issue by krissrex** [dvdciri/daggraph#26]
### Description
Trying to run `daggraph` exits with an exception.  
Node version: **v8.9.1** 
OS: Windows 10 

### Steps to reproduce
Run `daggraph`

### Expected behaviour
Graph generation without errors.

### Log

```
$ daggraph
Analyzing dagger components and modules..
TypeError: pending.then is not a function
    at FileHound._searchAsync (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\filehound\lib\filehound.js:705:22)
    at tryCatcher (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\krire\AppData\Roaming\nvm\v8.9.1\node_modules\daggraph\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by smaslenko** [comment]
**Preconditions:**
Node v9.3.0
Dagger2
**Actual result:**

> Analyzing dagger components and modules..
TypeError: pending.then is not a function
    at FileHound._searchAsync (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\filehound\lib\filehound.js:705:22)
    at tryCatcher (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\ispst\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)

**Comment by dvdciri** [comment]
Tried to reproduce it but without any success, it seems like a bug in the filehound lib as far as i can see. Will try to investigate it

**Comment by dvdciri** [comment]
Just tried upgrading to node version v9.2.1 and it works. No problems with that, try updating to the latest version and if you have the same issue provide more context as i've no idea how to reproduce this.

**Comment by smaslenko** [comment]
Can you please test it on this project https://github.com/smaslenko/nest-api-demo

**Comment by krissrex** [comment]
I get the same error on **v9.2.1**. @dvdciri are you running it on windows?

**Comment by smaslenko** [comment]
@krissrex yes, Windows 10 64-bit

**Comment by juandiana** [comment]
I'm experiencing the same problem. Using node v9.4.0.

**Comment by BrianOdisho** [comment]
Same error on Windows 10 64-bit with node v9.5.0

**Comment by N-i-p-o-l** [comment]
```
TypeError: pending.then is not a function
    at FileHound._searchAsync (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\filehound\lib\filehound.js:705:22)
    at tryCatcher (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\NiPoL\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
```

Node v9.6.1 version
npm 5.6.0

Please help

**Comment by MarkNjunge** [comment]
Same error.  

Windows 10 64-bit, Node 10.15.0

```
Analyzing dagger components and modules..
TypeError: pending.then is not a function
    at FileHound._searchAsync (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\filehound\lib\filehound.js:705:22)
    at tryCatcher (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:30:10)
    at _drainQueueStep (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Mark Kamau\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by amk9978** [comment]
Hi!
A long time has passed and I can't use this repository because of this problem,
Won't be solved?

**Comment by N-i-p-o-l** [comment]
Same problem node v.10.16.3 Windows 10 x64

**Comment by vberezkin** [comment]
Same problem

**Comment by agoztin** [comment]
I know this issue was closed but I find a solution, simply invoke daggraph with a dot "." to pass the cwd
$ daggraph .
