### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by piotrek-chmielowski** [dvdciri/daggraph#47]
While running `daggraph` in the top level directory of Android project I'm getting:

```
/usr/local/lib/node_modules/daggraph/src/dagger/DaggerAnalyzer.js:13
async function findComponents(projectRootPath){
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/daggraph/src/router.js:7:25)
```

Output of `npm --version` is `3.5.2`. Are there any further information I can provide to help you with reproducing the issue?

**Comment by dvdciri** [comment]
For now I would suggest to update the node version to the latest one and everything should work as expected. 
We're working to support previous node version for the async operations.

**Comment by dvdciri** [comment]
Can you please double check if you still have the issue with the new release 0.3.3? Thanks

**Comment by dvdciri** [comment]
Closing due to inactivity
