### ISSUE TITLE
Unable to see graph on browser

### ISSUE THREAD

**Issue by buddhasaikia** [dvdciri/daggraph#48]
### Description
Found the following error on inspect (Chrome browser)

```
Uncaught SyntaxError: Unexpected token A in JSON at position 68
    at JSON.parse (<anonymous>)
    at dependency_tree_graph.html:50
```
**dependency_tree_graph.html**
```
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.node {
  cursor: pointer;
}

.node circle {
  fill: #fff;
  stroke: steelblue;
  stroke-width: 1.5px;
}

.node text {
  font: 10px sans-serif;
}

.link {
  fill: none;
  stroke: #ccc;
  stroke-width: 1.5px;
}

</style>
<body>
<script src="https://d3js.org/d3.v3.min.js"></script>
<script>

var margin = {top: 20, right: 120, bottom: 20, left: 120},
    width = 960 - margin.right - margin.left,
    height = 800 - margin.top - margin.bottom;

var i = 0,
    duration = 750,
    root;

var tree = d3.layout.tree()
    .size([height, width]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("body").append("svg")
    .attr("width", width + margin.right + margin.left)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

const flare = JSON.parse(`{
  "name": "Dependencies",
  "children": [
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\di\\module\\ActivityBindingModule_MyFlightsActivity"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\di\\module\\ActivityBindingModule_OnBoardingActivity"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\di\\module\\ActivityBindingModule_UserProfileActivity"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\module\\home\\MyFlightsModule_MyFlightsFragment"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\module\\onBoarding\\OnBoardingModule_OnboardingFragment"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\build\\generated\\source\\apt\\dev\\debug\\com\\packagename\\module\\profile\\UserProfileModule_UserProfileFragment"
    },
    {
      "name": "I:\\AndroidStudioProjects\\projectname\\app\\src\\main\\java\\com\\packagename\\di\\components\\AppComponent",
      "children": [
        {
          "name": "AndroidSupportInjectionModule"
        }
      ]
    }
  ]
}`);
root = flare;
root.x0 = height / 2;
root.y0 = 0;

function collapse(d) {
if (d.children) {
    d._children = d.children;
    d._children.forEach(collapse);
    d.children = null;
}
}

root.children.forEach(collapse);
update(root);


d3.select(self.frameElement).style("height", "800px");

function update(source) {

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
      links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d) { d.y = d.depth * 180; });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .on("click", click);

  nodeEnter.append("circle")
      .attr("r", 1e-6)
      .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeEnter.append("text")
      .attr("x", function(d) { return d.children || d._children ? -10 : 10; })
      .attr("dy", ".35em")
      .attr("text-anchor", function(d) { return d.children || d._children ? "end" : "start"; })
      .text(function(d) { return d.name; })
      .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
      .attr("r", 4.5)
      .style("fill", function(d) { return d._children ? "lightsteelblue" : "#fff"; });

  nodeUpdate.select("text")
      .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position.
  var nodeExit = node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .remove();

  nodeExit.select("circle")
      .attr("r", 1e-6);

  nodeExit.select("text")
      .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      });

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {
  if (d.children) {
    d._children = d.children;
    d.children = null;
  } else {
    d.children = d._children;
    d._children = null;
  }
  update(d);
}

</script>
```

**Comment by dvdciri** [comment]
Do you have a public repository or a project that you can send me so I can try to reproduce this issue?

**Comment by buddhasaikia** [comment]
Aah! Sorry bro, that was not a public repo. I will test it on a public repo & let you know. Thanks

**Comment by buddhasaikia** [comment]
Now I am receiving this error while running ```daggraph``` from current project directory-

 command-
```
Analyzing dagger components and modules..
TypeError: pending.then is not a function
    at FileHound._searchAsync (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\filehound\lib\filehound.js:705:22)
    at tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user\AppData\Roaming\npm\node_modules\daggraph\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Comment by szczepanskikrs** [comment]
Same issue here, on Windows 10 browser has same issue 
```
Uncaught SyntaxError: Unexpected token K in JSON at position 55
    at JSON.parse (<anonymous>)
    at dependency_tree_graph.html:75
```

Unfortunately I can't grant you access to repository. What is funny actually on Linux Mint site gets generated perfectly and works like a charm.

**Comment by egorikftp** [comment]
@dvdciri Hello, I have the same problem with parsing. You can reproduce this issue with my project:

https://github.com/egorikftp/Lady-happy

**Comment by dvdciri** [comment]
Can you please double check if you still have the issue with the new release 0.3.3? Thanks

**Comment by egorikftp** [comment]
@dvdciri Still reproduces with the same error. Thanks

**Comment by kheldiente** [comment]
I am able to show the graph by not using JSON.parse() and assigning it directly to the variable.
From:
const flare = JSON.parse(`{
"children": []
}`)

To:
const flare = {
"children": []
}

**Comment by kheldiente** [comment]
I am able to show the graph by not using JSON.parse() and assigning it directly to the variable.
From:
` const flare = JSON.parse("{"children": []}") `

To:
` const flare = {"children": []} `

**Comment by dvdciri** [comment]
Create, maybe we can do this change, if you fancy open a PR feel free!
Thanks
